[package]
name = "rust_processing"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
psutil = "3.3.0"
rand = "0.8.5"
serde = "1.0.213"
serde_derive = "1.0.213"
sysinfo = "0.32.0"
time = "0.3.36"
